export const projectInfo = {
  title: 'Reclaim Seoul Wasp Atlas Explorer',
  shortTitle: 'Reclaim Seoul',
  edition: 'AA Visiting School Seoul 2026',
  school: 'AA Visiting School Seoul 2026',
  workshop: 'Reclaim Seoul',
  unit: 'Unit 3',
  unitTitle: 'Reclaim Seoul: Combinatorial Material Reuse for a Temporal City',
  tutors: ['Andrea Rossi', 'Hyo Wook Kim'],
  subtitle: 'Workshop edition of Wasp Atlas',
  description:
    'A workshop-specific Wasp Atlas Explorer for Reclaim Seoul, Unit 3 of AA Visiting School Seoul 2026, adapted from the original open-source Wasp Atlas project.',
  schoolUrl: 'https://www.social-algorithms.com/whats-on',
  unitUrl: 'https://www.social-algorithms.com/whats-on/2026-unit-3',
  currentRepoUrl: 'https://github.com/ReclaimSeoul/Wasp-Atlas-Explorer',
  datasetRepoUrl: 'https://github.com/ReclaimSeoul/Reclaimed-Design-Systems',
  originalExplorerUrl: 'https://github.com/Wasp-Framework/Wasp-Atas-Explorer',
  originalAtlasUrl: 'https://github.com/Wasp-Framework/Wasp-Atlas',
  waspPluginUrl: 'https://github.com/ar0551/Wasp',
  waspFood4RhinoUrl: 'https://www.food4rhino.com/en/app/wasp',
  webwaspjsUrl: 'https://github.com/winroger/waspjs',
  submitDatasetUrl: 'https://forms.gle/SYdRbsySKonq19GJ8',
  contactEmail: 'andrea@thecomputationalhive.com',
} as const;
